[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = [
    '@openzeppelin/=lib/openzeppelin-contracts/',
    '@ccip/=lib/chainlink-ccip/',
    '@chainlink-local/=lib/chainlink-local/'
]
[rpc_endpoints]
eth = "https://ethereum-sepolia.publicnode.com"
arb = "https://arbitrum-sepolia.publicnode.com"
# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
